id: c203e1581dc9412a858d46b85e615f92
inintial_creation_type: ocr
source_metadata:
  id: bdr:W2KG210295
  title: བཀའ་འགྱུར། ༼ཕུག་བྲག་བྲིས་མ༽
  volume:
    f90ed59df8ab40ff99a28100542dd63b:
      image_group_id: I2KG210405
      title: ''
      volume_number: 1
      total_pages: 0
    f23a16b998da41f9bbad5f5c70bf0950:
      image_group_id: I2KG210406
      title: ''
      volume_number: 2
      total_pages: 0
    f64784ffb4734881a475e17966ca266f:
      image_group_id: I2KG210407
      title: ''
      volume_number: 3
      total_pages: 0
    dc4993e433e145bf9907305efa77caef:
      image_group_id: I2KG210408
      title: ''
      volume_number: 4
      total_pages: 0
    60d86502920c432bbf21c30aa4c9a841:
      image_group_id: I2KG210409
      title: ''
      volume_number: 5
      total_pages: 0
    16a24c68ed764cba8454d4c0235ea315:
      image_group_id: I2KG210410
      title: ''
      volume_number: 6
      total_pages: 0
    5b0cf02b39b641c3922dfede69e9a66c:
      image_group_id: I2KG210411
      title: ''
      volume_number: 7
      total_pages: 0
    8a1d3e22f1a147c3a5d8398d1a140b81:
      image_group_id: I2KG210412
      title: ''
      volume_number: 8
      total_pages: 0
    4b54a48e44804682993a5862421c2252:
      image_group_id: I2KG210413
      title: ''
      volume_number: 9
      total_pages: 0
    343f048b3dcc4752881c0b92257c92a8:
      image_group_id: I2KG210414
      title: ''
      volume_number: 10
      total_pages: 0
    610535fe6291453ebd7be2f97b8a72c6:
      image_group_id: I2KG210415
      title: ''
      volume_number: 11
      total_pages: 0
    8a36f90f3cf14ce5be0aa52a2af50c86:
      image_group_id: I2KG210416
      title: ''
      volume_number: 12
      total_pages: 0
    eced8d38a3c64654a5f4b9264312a321:
      image_group_id: I2KG210417
      title: ''
      volume_number: 13
      total_pages: 0
    26668235323c46fa9722bd9def0247cf:
      image_group_id: I2KG210418
      title: ''
      volume_number: 14
      total_pages: 0
    69f06d7348dd4468a4b7f1c6c8987e20:
      image_group_id: I2KG210419
      title: ''
      volume_number: 15
      total_pages: 0
    7297974d27b8423a96095822f030d908:
      image_group_id: I2KG210420
      title: ''
      volume_number: 16
      total_pages: 0
    5fb5bc26f17845999c4eb0e19ba2dd11:
      image_group_id: I2KG210421
      title: ''
      volume_number: 17
      total_pages: 0
    ad435c30ff0d45d992da72f38fcf8836:
      image_group_id: I2KG210422
      title: ''
      volume_number: 18
      total_pages: 0
    e6d010da375346958416ea7860f54101:
      image_group_id: I2KG210423
      title: ''
      volume_number: 19
      total_pages: 0
    9bc1da4614ec49da8f104782089e28d8:
      image_group_id: I2KG210424
      title: ''
      volume_number: 20
      total_pages: 0
    3b0f85f819a541dd92f6920e937f29de:
      image_group_id: I2KG210425
      title: ''
      volume_number: 21
      total_pages: 0
    d198847ce38b4316aeeb74f5c9c42524:
      image_group_id: I2KG210426
      title: ''
      volume_number: 22
      total_pages: 0
    452c44b88d6540a0b95e45dd4486da96:
      image_group_id: I2KG210427
      title: ''
      volume_number: 23
      total_pages: 0
    b52131e28d074d0faea86702c6cb4846:
      image_group_id: I2KG210428
      title: ''
      volume_number: 24
      total_pages: 0
    07255be59670489d90911b83d2c95c62:
      image_group_id: I2KG210429
      title: ''
      volume_number: 25
      total_pages: 0
    e8e1c47ee54f429a91300d0995165325:
      image_group_id: I2KG210430
      title: ''
      volume_number: 26
      total_pages: 0
    1c3eaf14e4034fdb9292f1bb9c26afd1:
      image_group_id: I2KG210431
      title: ''
      volume_number: 27
      total_pages: 0
    443c24818a7d46ce85fac70c1c85b98a:
      image_group_id: I2KG210432
      title: ''
      volume_number: 28
      total_pages: 0
    fc83c8836b9243a480e0960042368431:
      image_group_id: I2KG210433
      title: ''
      volume_number: 29
      total_pages: 0
    523008cef4f24b99b3aa9f8b3f3a790e:
      image_group_id: I2KG210434
      title: ''
      volume_number: 30
      total_pages: 0
    dcc557811e4143d89edbde5475b2823a:
      image_group_id: I2KG210435
      title: ''
      volume_number: 31
      total_pages: 0
    e357d4b7045e41f49bdd35ce338729eb:
      image_group_id: I2KG210436
      title: ''
      volume_number: 32
      total_pages: 0
    51b1d01180fd409eae6d6c48ed2f0ba2:
      image_group_id: I2KG210437
      title: ''
      volume_number: 33
      total_pages: 0
    e9744ff5fddb41309ec5d2e341b0f53f:
      image_group_id: I2KG210438
      title: ''
      volume_number: 34
      total_pages: 0
    4d5a79debb934a47b48befda9c5b1c3f:
      image_group_id: I2KG210439
      title: ''
      volume_number: 35
      total_pages: 0
    7e20e91e417d4debaa3b6f96bc36c749:
      image_group_id: I2KG210440
      title: ''
      volume_number: 36
      total_pages: 0
    6680ff158c17422489f4f35511daf3e9:
      image_group_id: I2KG210441
      title: ''
      volume_number: 37
      total_pages: 0
    9b81f67a6ef94fe3982ef3f975825f32:
      image_group_id: I2KG210442
      title: ''
      volume_number: 38
      total_pages: 0
    d6f467162c524ba8b14a0bacca3995a8:
      image_group_id: I2KG210443
      title: ''
      volume_number: 39
      total_pages: 0
    51b876dd6afa4058a560d9629ad2e6b4:
      image_group_id: I2KG210444
      title: ''
      volume_number: 40
      total_pages: 0
    601466cf092045619137dcfe7cff54b0:
      image_group_id: I2KG210445
      title: ''
      volume_number: 41
      total_pages: 0
    05a05f96891047a096678aa24f251804:
      image_group_id: I2KG210446
      title: ''
      volume_number: 42
      total_pages: 0
    ba8dbecde76f405eae5ab030b17d8694:
      image_group_id: I2KG210447
      title: ''
      volume_number: 43
      total_pages: 0
    0cb197b96dbf4e92a8233cde461c9e5b:
      image_group_id: I2KG210448
      title: ''
      volume_number: 44
      total_pages: 0
    b841cc710aed4e6a94c6f05342720235:
      image_group_id: I2KG210449
      title: ''
      volume_number: 45
      total_pages: 0
    46086ac8779344e08fd5a3b0429cceb6:
      image_group_id: I2KG210450
      title: ''
      volume_number: 46
      total_pages: 0
    e7f8889a42be417bbc225b7aa6536d96:
      image_group_id: I2KG210451
      title: ''
      volume_number: 47
      total_pages: 0
    b17f0688db5f4e4491c1301953c799a2:
      image_group_id: I2KG210452
      title: ''
      volume_number: 48
      total_pages: 0
    7d4bc9651a314db59bdf0584edc26834:
      image_group_id: I2KG210453
      title: ''
      volume_number: 49
      total_pages: 0
    8a5d91e3e8c947c284eb315d8939b635:
      image_group_id: I2KG210454
      title: ''
      volume_number: 50
      total_pages: 0
    2ebbfc09726d4475b472cc069810e1e0:
      image_group_id: I2KG210455
      title: ''
      volume_number: 51
      total_pages: 0
    042fdd7fe5e648d5b3f9848572c59f13:
      image_group_id: I2KG210456
      title: ''
      volume_number: 52
      total_pages: 0
    5624552d547f48f5a6677cd1f5d9bdc2:
      image_group_id: I2KG210457
      title: ''
      volume_number: 53
      total_pages: 0
    3cc2560bb55346a8a698e7af032515fd:
      image_group_id: I2KG210458
      title: ''
      volume_number: 54
      total_pages: 0
    5e61b1d509814f6287121af9ac9c93ad:
      image_group_id: I2KG210459
      title: ''
      volume_number: 55
      total_pages: 0
    61b40a71a71549279c68255df2997cf6:
      image_group_id: I2KG210460
      title: ''
      volume_number: 56
      total_pages: 0
    7a6b406bf0c74fdc84b9c283481f7eab:
      image_group_id: I2KG210461
      title: ''
      volume_number: 57
      total_pages: 0
    58d84b043ead4419bfea6fbcceaf4391:
      image_group_id: I2KG210462
      title: ''
      volume_number: 58
      total_pages: 0
    f6cbcabc1346465e86fcbe86f371701a:
      image_group_id: I2KG210463
      title: ''
      volume_number: 59
      total_pages: 0
    830c23b56cde40c6a120bc2d40da1ae2:
      image_group_id: I2KG210464
      title: ''
      volume_number: 60
      total_pages: 0
    0ba90a1e1f624a95bc26b67e570e9dce:
      image_group_id: I2KG210465
      title: ''
      volume_number: 61
      total_pages: 0
    06cdb14d76a14dd08740a2a1959b60df:
      image_group_id: I2KG210466
      title: ''
      volume_number: 62
      total_pages: 0
    ea75b458746b434797088dff9d66dac4:
      image_group_id: I2KG210467
      title: ''
      volume_number: 63
      total_pages: 0
    9fc2c3392bdd477d940a6ed41774cf5e:
      image_group_id: I2KG210468
      title: ''
      volume_number: 64
      total_pages: 0
    a6d660d275ca475c86818378f53a5b83:
      image_group_id: I2KG210469
      title: ''
      volume_number: 65
      total_pages: 0
    f26a7579840d4c7683fd6f8b8e304951:
      image_group_id: I2KG210470
      title: ''
      volume_number: 66
      total_pages: 0
    ba5ebbf385674fbbbbd60d04e8decfb5:
      image_group_id: I2KG210471
      title: ''
      volume_number: 67
      total_pages: 0
    3cd1cbaa008e4db5b6eed0125cdfee48:
      image_group_id: I2KG210472
      title: ''
      volume_number: 68
      total_pages: 0
    5c2655f2236d4042b78788c7d752f8b7:
      image_group_id: I2KG210473
      title: ''
      volume_number: 69
      total_pages: 0
    304e06b38880403c9c040acac6709d00:
      image_group_id: I2KG210474
      title: ''
      volume_number: 70
      total_pages: 0
    98da71412aff4baaae7e1a201a299d36:
      image_group_id: I2KG210475
      title: ''
      volume_number: 71
      total_pages: 0
    217b734626d747f8b61939e5a999840b:
      image_group_id: I2KG210476
      title: ''
      volume_number: 72
      total_pages: 0
    02c05faf4a294a12a933c8c0fbdd85ec:
      image_group_id: I2KG210477
      title: ''
      volume_number: 73
      total_pages: 0
    651d5306448e4bb096671b5d6f966ecd:
      image_group_id: I2KG210478
      title: ''
      volume_number: 74
      total_pages: 0
    f6b04a10db564b27ab4630a3ad13eb54:
      image_group_id: I2KG210479
      title: ''
      volume_number: 75
      total_pages: 0
    334e105b9c3e4ab3a49a9f0dbeb16491:
      image_group_id: I2KG210480
      title: ''
      volume_number: 76
      total_pages: 0
    30a0d89a0f1c4fcf84fcd609ee96bea3:
      image_group_id: I2KG210481
      title: ''
      volume_number: 77
      total_pages: 0
    be5bb45c34274a97a10966580f5c3d51:
      image_group_id: I2KG210482
      title: ''
      volume_number: 78
      total_pages: 0
    6a56ec0f0cff4242b1eb05a2d6f2f04f:
      image_group_id: I2KG210483
      title: ''
      volume_number: 79
      total_pages: 0
    a71c735e36ce4c1aafb548f83fad0717:
      image_group_id: I2KG210484
      title: ''
      volume_number: 80
      total_pages: 0
    03e949c83e5f4739bd0cbe84457e8cf1:
      image_group_id: I2KG210485
      title: ''
      volume_number: 81
      total_pages: 0
    70cfc44631114951bca9cf18aec3c3a7:
      image_group_id: I2KG210486
      title: ''
      volume_number: 82
      total_pages: 0
    4a1bdeaa1100444c90855241404d117f:
      image_group_id: I2KG210487
      title: ''
      volume_number: 83
      total_pages: 0
    0b59dd05758c4756ae9f37a97b6ff084:
      image_group_id: I2KG210488
      title: ''
      volume_number: 84
      total_pages: 0
    d4674398b71841cb8e2afda0c5bc5d91:
      image_group_id: I2KG210489
      title: ''
      volume_number: 85
      total_pages: 0
    5a442d0775ae47b885c45c7ab371c129:
      image_group_id: I2KG210490
      title: ''
      volume_number: 86
      total_pages: 0
    f6dcc14584534f138bec244f2dc04244:
      image_group_id: I2KG210491
      title: ''
      volume_number: 87
      total_pages: 0
    c83bca2ce8184bdaa1056b6a3a42683f:
      image_group_id: I2KG210492
      title: ''
      volume_number: 88
      total_pages: 0
    cf6b7446de374304b35f396eeb295b58:
      image_group_id: I2KG210493
      title: ''
      volume_number: 89
      total_pages: 0
    058af2dfc07f45b88d6042a0aaa4eb62:
      image_group_id: I2KG210494
      title: ''
      volume_number: 90
      total_pages: 0
    c81316609dbb413a98a8a660737648fd:
      image_group_id: I2KG210495
      title: ''
      volume_number: 91
      total_pages: 0
    14c305982131445eba40bb7730689297:
      image_group_id: I2KG210496
      title: ''
      volume_number: 92
      total_pages: 0
    bc5421b85d434073bcd942c5eb209f35:
      image_group_id: I2KG210497
      title: ''
      volume_number: 93
      total_pages: 0
    05537969f52b45fab7873873be3298d3:
      image_group_id: I2KG210498
      title: ''
      volume_number: 94
      total_pages: 0
    aad707afa09d4e9b90c43b5faa6a4578:
      image_group_id: I2KG210499
      title: ''
      volume_number: 95
      total_pages: 0
    3dd41ae046934629a35c6b81380f8136:
      image_group_id: I2KG210500
      title: ''
      volume_number: 96
      total_pages: 0
    959e1b5eced54fc9b1df041bd89aa415:
      image_group_id: I2KG210501
      title: ''
      volume_number: 97
      total_pages: 0
    5cd4d4cccd804deeabedd536b96daec8:
      image_group_id: I2KG210502
      title: ''
      volume_number: 98
      total_pages: 0
    238117fbde374e658d0100ed24061124:
      image_group_id: I2KG210503
      title: ''
      volume_number: 99
      total_pages: 0
    a8cc2ea6587149fa9b0e78824045e337:
      image_group_id: I2KG210504
      title: ''
      volume_number: 100
      total_pages: 0
    836293fec5e64a43901b772ca9715421:
      image_group_id: I2KG210505
      title: ''
      volume_number: 101
      total_pages: 0
    f5156dd3a59c44099c6852dfd09e0479:
      image_group_id: I2KG210506
      title: ''
      volume_number: 102
      total_pages: 0
    1f1f004d38b24896b7dbcc17ba325cf7:
      image_group_id: I2KG210507
      title: ''
      volume_number: 103
      total_pages: 0
    37132c1f347c4a4a96d314071ca88d3b:
      image_group_id: I2KG210508
      title: ''
      volume_number: 104
      total_pages: 0
    d37c8aa0c8c4462ba3a60f39461023dc:
      image_group_id: I2KG210509
      title: ''
      volume_number: 105
      total_pages: 0
    1f1e5dbf96354104a077a5e074c0deb0:
      image_group_id: I2KG210510
      title: ''
      volume_number: 106
      total_pages: 0
    426e994909cb4dd78205b4cf91642983:
      image_group_id: I2KG210511
      title: ''
      volume_number: 107
      total_pages: 0
    250a7005f41a42c38dbb84250e824d7b:
      image_group_id: I2KG210512
      title: ''
      volume_number: 108
      total_pages: 0
    af0ee1622b194beead4e40bf39aefbec:
      image_group_id: I2KG210513
      title: ''
      volume_number: 109
      total_pages: 0
    e24a2f3cb854405eb9c1250876314e07:
      image_group_id: I2KG210514
      title: ''
      volume_number: 110
      total_pages: 0
    84fce8cc7f7f4a06bf0714746e2c5c43:
      image_group_id: I2KG210515
      title: ''
      volume_number: 111
      total_pages: 0
    8106af641ba54236b620bb327fb5a3c1:
      image_group_id: I2KG210516
      title: ''
      volume_number: 112
      total_pages: 0
    cfab9365981140e08dcb29beba79e492:
      image_group_id: I2KG210517
      title: ''
      volume_number: 113
      total_pages: 0
    60e45d5989654df09c88692f6eabe992:
      image_group_id: I2KG210518
      title: ''
      volume_number: 114
      total_pages: 0
    82498c68c2064998b5d29e036b95c3bd:
      image_group_id: I2KG210519
      title: ''
      volume_number: 115
      total_pages: 0
    596e70e26a484478a66cff3c8b29ddf4:
      image_group_id: I2KG210520
      title: ''
      volume_number: 116
      total_pages: 0
    4b38e9a66af04a0ba9d1f2ecf2f9a900:
      image_group_id: I2KG210521
      title: ''
      volume_number: 117
      total_pages: 0
    55a4a69779704afb9a59975f8c7d419a:
      image_group_id: I2KG210522
      title: ''
      volume_number: 118
      total_pages: 0
    7c911c470f3848abb3977b6acaa796c1:
      image_group_id: I2KG210523
      title: ''
      volume_number: 119
      total_pages: 0
    2d242d4dcda94190aa4b51e4215a412d:
      image_group_id: I2KG210524
      title: ''
      volume_number: 120
      total_pages: 0
  author: ''
